const types = {
  GET_POSTS: "PROVIDER_POSTS/GET_POSTS",
  GET_POSTS_REQUEST: "PROVIDER_POSTS/GET_POSTS_REQUEST",
  GET_POSTS_FAILURE: "PROVIDER_POSTS/GET_POSTS_FAILURE",
  GET_POSTS_SUCCESS: "PROVIDER_POSTS/GET_POSTS_SUCCESS",

  GET_POST_TO_EDIT: "PROVIDER_POSTS/GET_POST_TO_EDIT",
  GET_POST_TO_EDIT_REQUEST: "PROVIDER_POSTS/GET_POST_TO_EDIT_REQUEST",
  GET_POST_TO_EDIT_FAILURE: "PROVIDER_POSTS/GET_POST_TO_EDIT_FAILURE",
  GET_POST_TO_EDIT_SUCCESS: "PROVIDER_POSTS/GET_POST_TO_EDIT_SUCCESS",

  POST_POST: "PROVIDER_POSTS/POST_POST",
  POST_POST_REQUEST: "PROVIDER_POSTS/POST_POST_REQUEST",
  POST_POST_FAILURE: "PROVIDER_POSTS/POST_POST_FAILURE",
  POST_POST_SUCCESS: "PROVIDER_POSTS/POST_POST_SUCCESS",

  DELETE_POST: "PROVIDER_POSTS/DELETE_POST",
  DELETE_POST_REQUEST: "PROVIDER_POSTS/DELETE_POST_REQUEST",
  DELETE_POST_FAILURE: "PROVIDER_POSTS/DELETE_POST_FAILURE",
  DELETE_POST_SUCCESS: "PROVIDER_POSTS/DELETE_POST_SUCCESS",

  REQUEST_PUBLISH: "PROVIDER_POSTS/REQUEST_PUBLISH",
  REQUEST_PUBLISH_REQUEST: "PROVIDER_POSTS/REQUEST_PUBLISH_REQUEST",
  REQUEST_PUBLISH_FAILURE: "PROVIDER_POSTS/REQUEST_PUBLISH_FAILURE",
  REQUEST_PUBLISH_SUCCESS: "PROVIDER_POSTS/REQUEST_PUBLISH_SUCCESS",

  SHOW_PREVIEW: "PROVIDER_POSTS/SHOW_PREVIEW",
  SHOW_PREVIEW_REQUEST: "PROVIDER_POSTS/SHOW_PREVIEW_REQUEST",
  SHOW_PREVIEW_FAILURE: "PROVIDER_POSTS/SHOW_PREVIEW_FAILURE",
  SHOW_PREVIEW_SUCCESS: "PROVIDER_POSTS/SHOW_PREVIEW_SUCCESS",

  RESET_EDITING_POST: "PROVIDER_POSTS/RESET_EDITING_POST"
};

export default types;
