const types = {
  GET_PRODUCTS: "PROVIDER_PRODUCTS/GET_PRODUCTS",
  GET_PRODUCTS_REQUEST: "PROVIDER_PRODUCTS/GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_FAILURE: "PROVIDER_PRODUCTS/GET_PRODUCTS_FAILURE",
  GET_PRODUCTS_SUCCESS: "PROVIDER_PRODUCTS/GET_PRODUCTS_SUCCESS",

  GET_PRODUCT_TO_EDIT: "PROVIDER_PRODUCTS/GET_PRODUCT_TO_EDIT",
  GET_PRODUCT_TO_EDIT_REQUEST: "PROVIDER_PRODUCTS/GET_PRODUCT_TO_EDIT_REQUEST",
  GET_PRODUCT_TO_EDIT_FAILURE: "PROVIDER_PRODUCTS/GET_PRODUCT_TO_EDIT_FAILURE",
  GET_PRODUCT_TO_EDIT_SUCCESS: "PROVIDER_PRODUCTS/GET_PRODUCT_TO_EDIT_SUCCESS",

  POST_PRODUCT: "PROVIDER_PRODUCTS/POST_PRODUCT",
  POST_PRODUCT_REQUEST: "PROVIDER_PRODUCTS/POST_PRODUCT_REQUEST",
  POST_PRODUCT_FAILURE: "PROVIDER_PRODUCTS/POST_PRODUCT_FAILURE",
  POST_PRODUCT_SUCCESS: "PROVIDER_PRODUCTS/POST_PRODUCT_SUCCESS",

  DELETE_PRODUCT: "PROVIDER_PRODUCTS/DELETE_PRODUCT",
  DELETE_PRODUCT_REQUEST: "PROVIDER_PRODUCTS/DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_FAILURE: "PROVIDER_PRODUCTS/DELETE_PRODUCT_FAILURE",
  DELETE_PRODUCT_SUCCESS: "PROVIDER_PRODUCTS/DELETE_PRODUCT_SUCCESS",

  REQUEST_PUBLISH: "PROVIDER_PRODUCTS/REQUEST_PUBLISH",
  REQUEST_PUBLISH_REQUEST: "PROVIDER_PRODUCTS/REQUEST_PUBLISH_REQUEST",
  REQUEST_PUBLISH_FAILURE: "PROVIDER_PRODUCTS/REQUEST_PUBLISH_FAILURE",
  REQUEST_PUBLISH_SUCCESS: "PROVIDER_PRODUCTS/REQUEST_PUBLISH_SUCCESS",

  SHOW_PREVIEW: "PROVIDER_PRODUCTS/SHOW_PREVIEW",
  SHOW_PREVIEW_REQUEST: "PROVIDER_PRODUCTS/SHOW_PREVIEW_REQUEST",
  SHOW_PREVIEW_FAILURE: "PROVIDER_PRODUCTS/SHOW_PREVIEW_FAILURE",
  SHOW_PREVIEW_SUCCESS: "PROVIDER_PRODUCTS/SHOW_PREVIEW_SUCCESS",

  RESET_EDITING_PRODUCT: "PROVIDER_PRODUCTS/RESET_EDITING_PRODUCT"
};

export default types;
