export default {
  CHANGE_STEP: "SIGNUP/CHANGE_STEP",
  SET_FIELD: "SIGNUP/SET_FIELD",
  REGISTER_PHONE: "SIGNUP/REGISTER_PHONE",
  REGISTER_PHONE_REQUEST: "SIGNUP/REGISTER_PHONE_REQUEST",
  REGISTER_PHONE_SUCCESS: "SIGNUP/REGISTER_PHONE_SUCCESS",
  REGISTER_PHONE_FAILURE: "SIGNUP/REGISTER_PHONE_FAILURE",
  VERIFY_PHONE: "SIGNUP/VERIFY_PHONE",
  VERIFY_PHONE_SUCCESS: "SIGNUP/VERIFY_PHONE_SUCCESS",
  REGISTER_EMAIL: "SIGNUP/REGISTER_EMAIL",
  FINISH_SIGNUP: "SIGNUP/FINISH_SIGNUP"
};
