const types = {
  GET_ACCOUNT: "ACCOUNT/GET_ACCOUNT",
  GET_ACCOUNT_REQUEST: "ACCOUNT/GET_ACCOUNT_REQUEST",
  GET_ACCOUNT_FAILURE: "ACCOUNT/GET_ACCOUNT_FAILURE",
  GET_ACCOUNT_SUCCESS: "ACCOUNT/GET_ACCOUNT_SUCCESS",

  POST_ACCOUNT: "ACCOUNT/POST_ACCOUNT",
  POST_ACCOUNT_REQUEST: "ACCOUNT/POST_ACCOUNT_REQUEST",
  POST_ACCOUNT_FAILURE: "ACCOUNT/POST_ACCOUNT_FAILURE",
  POST_ACCOUNT_SUCCESS: "ACCOUNT/POST_ACCOUNT_SUCCESS",

  GET_ADDRESSES: "ACCOUNT/GET_ADDRESSES",
  GET_ADDRESSES_REQUEST: "ACCOUNT/GET_ADDRESSES_REQUEST",
  GET_ADDRESSES_FAILURE: "ACCOUNT/GET_ADDRESSES_FAILURE",
  GET_ADDRESSES_SUCCESS: "ACCOUNT/GET_ADDRESSES_SUCCESS",

  SAVE_ADDRESS_FROM_MAP: "ACCOUNT/SAVE_ADDRESS_FROM_MAP",

  EDIT_ADDRESS: "ACCOUNT/EDIT_ADDRESS",

  POST_ADDRESS: "ACCOUNT/POST_ADDRESS",
  POST_ADDRESS_REQUEST: "ACCOUNT/POST_ADDRESS_REQUEST",
  POST_ADDRESS_FAILURE: "ACCOUNT/POST_ADDRESS_FAILURE",
  POST_ADDRESS_SUCCESS: "ACCOUNT/POST_ADDRESS_SUCCESS",

  DELETE_ADDRESS: "ACCOUNT/DELETE_ADDRESS",
  DELETE_ADDRESS_REQUEST: "ACCOUNT/DELETE_ADDRESS_REQUEST",
  DELETE_ADDRESS_FAILURE: "ACCOUNT/DELETE_ADDRESS_FAILURE",
  DELETE_ADDRESS_SUCCESS: "ACCOUNT/DELETE_ADDRESS_SUCCESS",

  SET_ACTIVE: "ADDRESS/SET_ACTIVE",
  SET_ACTIVE_REQUEST: "ADDRESS/SET_ACTIVE_REQUEST",
  SET_ACTIVE_FAILURE: "ADDRESS/SET_ACTIVE_FAILURE",
  SET_ACTIVE_SUCCESS: "ADDRESS/SET_ACTIVE_SUCCESS"
};

export default types;
