const types = {
  GET_SERVICES: "PROVIDER_SERVICES/GET_SERVICES",
  GET_SERVICES_REQUEST: "PROVIDER_SERVICES/GET_SERVICES_REQUEST",
  GET_SERVICES_FAILURE: "PROVIDER_SERVICES/GET_SERVICES_FAILURE",
  GET_SERVICES_SUCCESS: "PROVIDER_SERVICES/GET_SERVICES_SUCCESS",

  GET_SERVICE_TO_EDIT: "PROVIDER_SERVICES/GET_SERVICE_TO_EDIT",
  GET_SERVICE_TO_EDIT_REQUEST: "PROVIDER_SERVICES/GET_SERVICE_TO_EDIT_REQUEST",
  GET_SERVICE_TO_EDIT_FAILURE: "PROVIDER_SERVICES/GET_SERVICE_TO_EDIT_FAILURE",
  GET_SERVICE_TO_EDIT_SUCCESS: "PROVIDER_SERVICES/GET_SERVICE_TO_EDIT_SUCCESS",

  POST_SERVICE: "PROVIDER_SERVICES/POST_SERVICE",
  POST_SERVICE_REQUEST: "PROVIDER_SERVICES/POST_SERVICE_REQUEST",
  POST_SERVICE_FAILURE: "PROVIDER_SERVICES/POST_SERVICE_FAILURE",
  POST_SERVICE_SUCCESS: "PROVIDER_SERVICES/POST_SERVICE_SUCCESS",

  DELETE_SERVICE: "PROVIDER_SERVICES/DELETE_SERVICE",
  DELETE_SERVICE_REQUEST: "PROVIDER_SERVICES/DELETE_SERVICE_REQUEST",
  DELETE_SERVICE_FAILURE: "PROVIDER_SERVICES/DELETE_SERVICE_FAILURE",
  DELETE_SERVICE_SUCCESS: "PROVIDER_SERVICES/DELETE_SERVICE_SUCCESS",

  REQUEST_PUBLISH: "PROVIDER_SERVICES/REQUEST_PUBLISH",
  REQUEST_PUBLISH_REQUEST: "PROVIDER_SERVICES/REQUEST_PUBLISH_REQUEST",
  REQUEST_PUBLISH_FAILURE: "PROVIDER_SERVICES/REQUEST_PUBLISH_FAILURE",
  REQUEST_PUBLISH_SUCCESS: "PROVIDER_SERVICES/REQUEST_PUBLISH_SUCCESS",

  SHOW_PREVIEW: "PROVIDER_SERVICES/SHOW_PREVIEW",
  SHOW_PREVIEW_REQUEST: "PROVIDER_SERVICES/SHOW_PREVIEW_REQUEST",
  SHOW_PREVIEW_FAILURE: "PROVIDER_SERVICES/SHOW_PREVIEW_FAILURE",
  SHOW_PREVIEW_SUCCESS: "PROVIDER_SERVICES/SHOW_PREVIEW_SUCCESS",

  RESET_EDITING_SERVICE: "PROVIDER_SERVICES/RESET_EDITING_SERVICE"
};

export default types;
