const types = {
  REQUEST_TO_BE_PROVIDER: "SERVICE_PROVIDER/REQUEST_TO_BE_PROVIDER",

  GET_ACCOUNT: "SERVICE_PROVIDER/GET_ACCOUNT",
  GET_ACCOUNT_REQUEST: "SERVICE_PROVIDER/GET_ACCOUNT_REQUEST",
  GET_ACCOUNT_FAILURE: "SERVICE_PROVIDER/GET_ACCOUNT_FAILURE",
  GET_ACCOUNT_SUCCESS: "SERVICE_PROVIDER/GET_ACCOUNT_SUCCESS",

  POST_ACCOUNT: "SERVICE_PROVIDER/POST_ACCOUNT",
  POST_ACCOUNT_REQUEST: "SERVICE_PROVIDER/POST_ACCOUNT_REQUEST",
  POST_ACCOUNT_FAILURE: "SERVICE_PROVIDER/POST_ACCOUNT_FAILURE",
  POST_ACCOUNT_SUCCESS: "SERVICE_PROVIDER/POST_ACCOUNT_SUCCESS"
};

export default types;
